Problem: VirtualBox and wpa_gui crash on start
Error: Qt FATAL: Cannot mix incompatible Qt library (version 0x50902) with this library (version 0x50901)

Solution: revert to stable dropbox

It appears dropbox brought newer Qt (5.9.2) from unstable
but qtwebkit is still 5.9.1 and it is likely that this is
the reason for the error above.